export const reducerCases = {
  SET_VIDEO_CALL: "SET_VIDEO_CALL",
  SET_VOICE_CALL: "SET_VOICE_CALL",
  END_CALL: "END_CALL",
  SET_INCOMMING_VOICE_CALL: "SET_INCOMMING_VOICE_CALL",
  SET_INCOMMING_VIDEO_CALL: "SET_INCOMMING_VIDEO_CALL",
};
